	.cpu generic+fp+simd
	.file	"filter_v2.c"
	.text
.Ltext0:
	.cfi_sections	.debug_frame
.Letext0:
	.section	.debug_line,"",%progbits
.Ldebug_line0:
	.section	.debug_str,"MS",%progbits,1
.LASF0:
	.string	"/home2/terry/914/NVRSDK/linux-4.4.18"
.LASF1:
	.string	"net/rtl/fastpath/filter_v2.c"
.LASF2:
	.ascii	"GNU C 4.9.4 -mlittle-endian -mgeneral-regs-only -mabi=lp64 -"
	.ascii	"g -O2 -std=gnu90 -fno-strict-aliasing -fno-common -fno-async"
	.ascii	"hronous-unwind-tables -fno-pic -fno-delete-null-pointer-chec"
	.ascii	"ks -fno-reorder-bl"
	.string	"ocks -fno-tree-ch -fno-caller-saves -fno-stack-protector -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -femit-struct-debug-baseonly -fno-var-tracking -fno-strict-overflow -fconserve-stack --param allow-store-data-races=0"
	.ident	"GCC: (OpenWrt/Linaro GCC 4.9-2015.06 r46836) 4.9.4"
	.section	.note.GNU-stack,"",%progbits
