dtb-$(CONFIG_ARCH_RTD129x) += rtd1295-mele-v9.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd1295-probox2-ava.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd1295-zidoo-x9s.dtb

dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-bananapi-w2-2GB.dtb
